### ISSUE TITLE
"Hmmm... I rate this message "<the users message>" a <random number>/10"

### ISSUE THREAD

**Issue by robinhickmann** [SandwichBtw/crystal-bot#3]
The bot has a chance (maybe 5-10%) to reply to someone with "Hmmm... I rate this message "<the users message>" a <random number>/10"

**Comment by natereprogle** [comment]
@SandwichBtw I'll go ahead and get this, it's actually already done haha. Only took 4 lines of code

**Comment by natereprogle** [comment]
Completed in https://github.com/SandwichBtw/crystal-bot/commit/91d17ec372ed12e0b69db0fc8fee4cd92d80240f
